# Generated by Django 5.2.4 on 2025-09-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom unique de la catégorie de services (ex : 'Développement Web', 'Marketing Digital').", max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la catégorie.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du service ou du produit.', max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(help_text='Description complète des fonctionnalités et avantages du service.', verbose_name='Description détaillée')),
                ('prix', models.DecimalField(decimal_places=2, help_text="Prix du service. S'il s'agit d'un abonnement, c'est le prix unitaire (ex : par mois).", max_digits=10, verbose_name='Prix')),
                ('type_tarif', models.CharField(choices=[('ABONNEMENT_MENSUEL', 'Abonnement Mensuel'), ('FACTURATION_UNIQUE', 'Facturation Unique'), ('ABONNEMENT_ANNUEL', 'Abonnement Annuel')], help_text='Sélectionnez le type de tarification pour ce service (abonnement, facturation unique, etc.).', max_length=20, verbose_name='Type de tarification')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le service est actuellement disponible dans le catalogue.', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle ce service a été ajouté au catalogue.', verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification des informations du service.', verbose_name='Date de mise à jour')),
                ('categorie', models.ForeignKey(blank=True, help_text='Catégorie à laquelle ce service appartient.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue_service.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
            },
        ),
    ]
