# Generated by Django 5.2.4 on 2025-09-16 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date à laquelle cette catégorie a été créée.', verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix du service.', max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_tarif',
            field=models.CharField(choices=[('ABONNEMENT_MENSUEL', 'Abonnement Mensuel'), ('FACTURATION_UNIQUE', 'Facturation Unique'), ('ABONNEMENT_ANNUEL', 'Abonnement Annuel')], help_text='Sélectionnez le type de tarification pour ce service.', max_length=20, verbose_name='Type de tarification'),
        ),
    ]
