# Generated by Django 5.2.4 on 2025-09-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_service', '0002_categorie_date_creation_alter_service_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, help_text='Date de la dernière modification des informations de la catégorie.', verbose_name='Date de mise à jour'),
        ),
    ]
