# Generated by Django 5.2.4 on 2025-09-21 00:40

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue_service', '0002_categorie_date_creation_alter_service_prix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement.")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, help_text="Date et heure de modification de l'enregistrement.")),
                ('email', models.EmailField(help_text='Adresse e-mail unique du contact.', max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text='Numéro de téléphone unique du contact.', max_length=128, region=None, unique=True)),
                ('notes_supplementaires', models.TextField(blank=True, help_text='Notes internes ou informations supplémentaires concernant le contact.')),
                ('adresse', models.TextField(help_text='Adresse complète (rue, numéro, etc.).')),
                ('ville', models.CharField(help_text='Ville de résidence ou du siège social.', max_length=100)),
                ('code_postal', models.CharField(help_text="Code postal de l'adresse.", max_length=10)),
                ('pays', models.CharField(help_text="Pays de l'adresse.", max_length=100)),
                ('ice', models.CharField(help_text="Identifiant Commun de l'Entreprise (15 chiffres). Obligatoire.", max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^\\d{15}$', "L'ICE doit contenir exactement 15 chiffres.")], verbose_name='ICE')),
                ('statut_juridique', models.CharField(choices=[('SARL', 'SARL - Société à Responsabilité Limitée'), ('EURL', 'EURL - Entreprise Unipersonnelle à Responsabilité Limitée'), ('SAS', 'SAS - Société par Actions Simplifiée'), ('SASU', 'SASU - Société par Actions Simplifiée Unipersonnelle'), ('SA', 'SA - Société Anonyme'), ('SNC', 'SNC - Société en Nom Collectif'), ('SCS', 'SCS - Société en Commandite Simple'), ('SCA', 'SCA - Société en Commandite par Actions'), ('GIE', "GIE - Groupement d'Intérêt Économique"), ('Micro-entreprise', 'Micro-entreprise'), ('Association', 'Association (Loi 1901)'), ('Coopérative', 'Coopérative'), ('SCI', 'SCI - Société Civile Immobilière'), ('SCP', 'SCP - Société Civile Professionnelle'), ('Auto-entrepreneur', 'Auto-entrepreneur (ancien statut)'), ('Autre', 'Autre')], help_text="Forme juridique de l'entreprise (ex: SARL, SA, etc.).", max_length=32)),
                ('secteur_activite', models.CharField(choices=[('A', 'Agriculture, Sylviculture et Pêche'), ('B', 'Industries Extractives'), ('C', 'Industrie manufacturière'), ('D', 'Production et distribution d’eau et d’électricité'), ('E', 'Bâtiment et travaux publics (BTP)'), ('F', 'Commerce de gros et de détail'), ('G', 'Transports, entreposage et communications'), ('H', 'Services aux entreprises'), ('I', 'Services aux particuliers'), ('J', 'Enseignement, santé et action sociale'), ('K', 'Services publics'), ('L', 'Hébergement et restauration'), ('M', 'Activités financières et d’assurance'), ('N', 'Activités immobilières'), ('O', 'Autres activités de services')], help_text="Secteur d'activité principal de l'entreprise selon la nomenclature marocaine (NAM).", max_length=45)),
                ('nom_entreprise', models.CharField(help_text="Nom légal de l'entreprise.", max_length=200, unique=True)),
                ('website', models.URLField(blank=True, help_text="Adresse du site web de l'entreprise.", null=True, verbose_name='Site Web')),
                ('nombre_employes', models.CharField(blank=True, choices=[('micro', 'Moins de 10 employés (Micro-entreprise)'), ('petite', '10 à 49 employés (Petite Entreprise)'), ('moyenne', '50 à 249 employés (Moyenne Entreprise)'), ('grande', '250 employés ou plus (Grande Entreprise)')], help_text="Tranche du nombre d'employés dans l'entreprise selon la classification européenne.", max_length=10)),
                ('type_compte', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='prospect', help_text='Le type de relation avec cette entreprise.', max_length=20)),
                ('responsable', models.ForeignKey(blank=True, help_text='Utilisateur responsable de cette entreprise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises_gerees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement.")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, help_text="Date et heure de modification de l'enregistrement.")),
                ('email', models.EmailField(help_text='Adresse e-mail unique du contact.', max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text='Numéro de téléphone unique du contact.', max_length=128, region=None, unique=True)),
                ('notes_supplementaires', models.TextField(blank=True, help_text='Notes internes ou informations supplémentaires concernant le contact.')),
                ('adresse', models.TextField(help_text='Adresse complète (rue, numéro, etc.).')),
                ('ville', models.CharField(help_text='Ville de résidence ou du siège social.', max_length=100)),
                ('code_postal', models.CharField(help_text="Code postal de l'adresse.", max_length=10)),
                ('pays', models.CharField(help_text="Pays de l'adresse.", max_length=100)),
                ('civilite', models.CharField(choices=[('M', 'M.'), ('Mme', 'Mme')], help_text='Civilité du client (M., Mme).', max_length=5)),
                ('nom', models.CharField(help_text='Nom de famille du client.', max_length=100)),
                ('prenom', models.CharField(help_text='Prénom du client.', max_length=100)),
                ('date_de_naissance', models.DateField(help_text='Date de naissance du client.')),
                ('source', models.CharField(blank=True, choices=[('telephone', 'Appel Téléphonique'), ('web', 'Site Web'), ('recommandation', 'Recommandation'), ('salon', 'Salon ou Événement'), ('reseaux_sociaux', 'Réseaux Sociaux'), ('autre', 'Autre')], help_text="Source d'où provient ce contact (ex: site web, Appel téléphonique).", max_length=20)),
                ('type_relation', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='prospect', help_text='Le type de relation avec ce particulier.', max_length=20)),
                ('responsable', models.ForeignKey(blank=True, help_text='Utilisateur responsable de ce client particulier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='particuliers_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Particulier',
                'verbose_name_plural': 'Particuliers',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement.")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, help_text="Date et heure de modification de l'enregistrement.")),
                ('nom', models.CharField(help_text="Nom court pour l'opportunité.", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de ce que l'opportunité implique.")),
                ('statut', models.CharField(choices=[('qualification', 'Qualification'), ('negociation', 'Négociation'), ('gagnee', 'Gagnée'), ('perdue', 'Perdue')], help_text="Statut actuel de l'opportunité dans le processus de vente.", max_length=13)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text="Montant total de l'opportunité, mis à jour automatiquement.", max_digits=10, null=True)),
                ('client_entreprise', models.ForeignKey(blank=True, help_text='Client entreprise associé à cette opportunité.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunites_entreprise', to='gestion_commerciale.entreprise')),
                ('responsable', models.ForeignKey(blank=True, help_text='Utilisateur responsable du suivi de cette opportunité.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_gerees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Le service ou produit unique inclus dans cette opportunité.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to='catalogue_service.service', verbose_name='Service associé')),
                ('client_particulier', models.ForeignKey(blank=True, help_text='Client particulier associé à cette opportunité.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunites_particulier', to='gestion_commerciale.particulier')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='contact_principal',
            field=models.ForeignKey(blank=True, help_text="Personne de contact principale au sein de l'entreprise.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_commerciale.particulier'),
        ),
    ]
