# Generated by Django 5.2.4 on 2025-09-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commerciale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='source',
            field=models.CharField(blank=True, choices=[('telephone', 'Appel Téléphonique'), ('web', 'Site Web'), ('recommandation', 'Recommandation'), ('salon', 'Salon ou Événement'), ('reseaux_sociaux', 'Réseaux Sociaux'), ('autre', 'Autre')], help_text="Source d'où provient ce contact (ex: site web, Appel téléphonique).", max_length=20),
        ),
    ]
